on: [push]
jobs:
    test-alert-rules:
      runs-on: ubuntu-18.04
      steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Run promtool tests'
        uses: 'MatsuriJapon/promtool-action@v1'
        with:
          args: 'test rules $(find monitoring/prometheus -name *.yaml)'
